"""
Samples API — Demo Center
Serves sample log files and scenario metadata for the Demo Center.
"""
import logging
from pathlib import Path
from fastapi import APIRouter, HTTPException

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/samples", tags=["samples"])

SAMPLE_LOGS_DIR = Path(__file__).parent.parent.parent / "sample-logs"

SCENARIOS = [
    {
        "id": "db-connection-failure",
        "title": "Database Connection Failure",
        "description": "Application pods unable to reach the PostgreSQL service — connection refused on port 5432.",
        "filename": "01-db-connection-failure.log",
        "expected_incident": "DB_CONNECTION_FAILURE",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "DATABASE",
    },
    {
        "id": "dns-failure",
        "title": "DNS Resolution Failure",
        "description": "CoreDNS unavailable — services cannot resolve internal hostnames.",
        "filename": "02-dns-failure.log",
        "expected_incident": "DNS_FAILURE",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "NETWORKING",
    },
    {
        "id": "port-conflict",
        "title": "Port Conflict — Address Already In Use",
        "description": "Application fails to bind to port 8080 — another process is already using it.",
        "filename": "03-port-conflict.log",
        "expected_incident": "PORT_CONFLICT",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "NETWORKING",
    },
    {
        "id": "crashloopbackoff",
        "title": "CrashLoopBackOff",
        "description": "Pod enters a restart loop — container failing immediately on start.",
        "filename": "04-crashloopbackoff.log",
        "expected_incident": "CRASH_LOOP_BACKOFF",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "KUBERNETES",
    },
    {
        "id": "oomkilled",
        "title": "OOMKilled — Container Out of Memory",
        "description": "Container killed by the Linux OOM killer — memory limit exceeded.",
        "filename": "05-oomkilled.log",
        "expected_incident": "OOM_KILLED",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "RESOURCES",
    },
    {
        "id": "imagepullfailure",
        "title": "Image Pull Failure",
        "description": "Kubernetes cannot pull the container image — tag missing or registry auth failed.",
        "filename": "06-imagepullfailure.log",
        "expected_incident": "IMAGE_PULL_FAILURE",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "KUBERNETES",
    },
    {
        "id": "authentication-failure",
        "title": "Authentication Failure",
        "description": "Service authentication rejected — invalid credentials or expired token.",
        "filename": "07-authentication-failure.log",
        "expected_incident": "AUTHENTICATION_FAILURE",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "SECURITY",
    },
    {
        "id": "missing-configuration",
        "title": "Missing Configuration",
        "description": "Required environment variables missing — application cannot start.",
        "filename": "08-missing-configuration.log",
        "expected_incident": "MISSING_CONFIGURATION",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "CONFIGURATION",
    },
    {
        "id": "disk-full",
        "title": "Disk / Volume Full",
        "description": "PersistentVolume has no space left — write operations failing.",
        "filename": "09-disk-full.log",
        "expected_incident": "DISK_FULL",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "STORAGE",
    },
    {
        "id": "permission-denied",
        "title": "Permission Denied",
        "description": "Container lacks file system permissions — operation not permitted.",
        "filename": "10-permission-denied.log",
        "expected_incident": "PERMISSION_DENIED",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "SECURITY",
    },
    {
        "id": "root-cause-demo",
        "title": "Root Cause Demo — DB Failure Causing CrashLoop",
        "description": "DB connection failure propagates to CrashLoopBackOff. Demonstrates relationship bonus and root cause ranking.",
        "filename": "11-root-cause-demo.log",
        "expected_incident": "DB_CONNECTION_FAILURE",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "DATABASE",
    },
    # ── Application ─────────────────────────────────────────────────────────
    {
        "id": "application-startup-failure",
        "title": "Application Startup Failure",
        "description": "Service crashes immediately on boot — dependency not reachable during initialization.",
        "filename": "12-application-startup-failure.log",
        "expected_incident": "APPLICATION_STARTUP_FAILURE",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "APPLICATION",
    },
    {
        "id": "configuration-validation-failure",
        "title": "Configuration Validation Failure",
        "description": "ConfigMap contains invalid YAML schema — service refuses to start with bad config.",
        "filename": "13-configuration-validation-failure.log",
        "expected_incident": "CONFIGURATION_VALIDATION_FAILURE",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "CONFIGURATION",
    },
    # ── Kubernetes ───────────────────────────────────────────────────────────
    {
        "id": "pod-pending",
        "title": "Pod Stuck in Pending State",
        "description": "Scheduler cannot place pod — nodes have insufficient CPU and memory.",
        "filename": "14-pod-pending.log",
        "expected_incident": "POD_PENDING",
        "severity": "WARNING",
        "expected_status": "CONFIDENT",
        "category": "KUBERNETES",
    },
    {
        "id": "node-not-ready",
        "title": "Node Not Ready",
        "description": "Kubelet stopped reporting heartbeats — node marked NotReady and pods evicted.",
        "filename": "15-node-not-ready.log",
        "expected_incident": "NODE_NOT_READY",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "KUBERNETES",
    },
    {
        "id": "resource-quota-exceeded",
        "title": "ResourceQuota Exceeded",
        "description": "Namespace hard quota reached — new pods rejected by the API server.",
        "filename": "16-resource-quota-exceeded.log",
        "expected_incident": "RESOURCE_QUOTA_EXCEEDED",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "KUBERNETES",
    },
    {
        "id": "pod-evicted",
        "title": "Pod Evicted — Node Disk/Memory Pressure",
        "description": "Kubelet eviction manager removes pods to relieve node disk and memory pressure.",
        "filename": "17-pod-evicted.log",
        "expected_incident": "POD_EVICTED",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "KUBERNETES",
    },
    {
        "id": "liveness-probe-failure",
        "title": "Liveness Probe Failure",
        "description": "Container health check fails repeatedly — kubelet kills and restarts the container.",
        "filename": "18-liveness-probe-failure.log",
        "expected_incident": "LIVENESS_PROBE_FAILURE",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "KUBERNETES",
    },
    {
        "id": "readiness-probe-failure",
        "title": "Readiness Probe Failure",
        "description": "Pod fails readiness checks — removed from service endpoints, no traffic routed.",
        "filename": "19-readiness-probe-failure.log",
        "expected_incident": "READINESS_PROBE_FAILURE",
        "severity": "WARNING",
        "expected_status": "CONFIDENT",
        "category": "KUBERNETES",
    },
    # ── Database ─────────────────────────────────────────────────────────────
    {
        "id": "db-deadlock",
        "title": "Database Deadlock Detected",
        "description": "Concurrent transactions cause mutual lock contention — transactions rolled back.",
        "filename": "20-db-deadlock.log",
        "expected_incident": "DB_DEADLOCK",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "DATABASE",
    },
    {
        "id": "db-slow-query",
        "title": "Database Slow Query / Statement Timeout",
        "description": "Full table scan on 8M-row table exceeds statement timeout — query killed.",
        "filename": "21-db-slow-query.log",
        "expected_incident": "DB_SLOW_QUERY",
        "severity": "WARNING",
        "expected_status": "CONFIDENT",
        "category": "DATABASE",
    },
    {
        "id": "db-migration-failure",
        "title": "Database Migration Failure",
        "description": "Flyway migration script fails — schema in inconsistent state, service cannot start.",
        "filename": "22-db-migration-failure.log",
        "expected_incident": "DB_MIGRATION_FAILURE",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "DATABASE",
    },
    {
        "id": "db-replication-lag",
        "title": "Database Replication Lag",
        "description": "Read replica falls 2+ minutes behind primary — stale reads and connection failures.",
        "filename": "23-db-replication-lag.log",
        "expected_incident": "DB_REPLICATION_LAG",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "DATABASE",
    },
    # ── Cache / Redis ─────────────────────────────────────────────────────────
    {
        "id": "redis-oom",
        "title": "Redis Out of Memory",
        "description": "Redis maxmemory reached with noeviction policy — all write commands rejected.",
        "filename": "24-redis-oom.log",
        "expected_incident": "REDIS_OOM",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "CACHE",
    },
    {
        "id": "redis-connection-timeout",
        "title": "Redis Connection Timeout",
        "description": "Application cannot reach Redis — connection pool exhausted, service crashes.",
        "filename": "25-redis-connection-timeout.log",
        "expected_incident": "REDIS_CONNECTION_TIMEOUT",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "CACHE",
    },
    {
        "id": "redis-replication-broken",
        "title": "Redis Replication Broken",
        "description": "Replica loses sync with master — partial resynchronization fails repeatedly.",
        "filename": "26-redis-replication-broken.log",
        "expected_incident": "REDIS_REPLICATION_BROKEN",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "CACHE",
    },
    # ── Messaging ────────────────────────────────────────────────────────────
    {
        "id": "consumer-lag",
        "title": "Message Consumer Lag",
        "description": "Consumer group falls 25,000 messages behind — processing rate cannot keep up.",
        "filename": "27-consumer-lag.log",
        "expected_incident": "CONSUMER_LAG",
        "severity": "WARNING",
        "expected_status": "CONFIDENT",
        "category": "MESSAGING",
    },
    {
        "id": "message-broker-down",
        "title": "Message Broker Unavailable",
        "description": "All Kafka brokers unreachable — producers and consumers cannot connect.",
        "filename": "28-message-broker-down.log",
        "expected_incident": "MESSAGE_BROKER_DOWN",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "MESSAGING",
    },
    {
        "id": "queue-full",
        "title": "Message Queue / Topic Full",
        "description": "Kafka topic retention limit exceeded — producer buffer overflow, messages dropped.",
        "filename": "29-queue-full.log",
        "expected_incident": "QUEUE_FULL",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "MESSAGING",
    },
    # ── Cloud / IAM ──────────────────────────────────────────────────────────
    {
        "id": "cloud-iam-denied",
        "title": "Cloud IAM Authorization Denied",
        "description": "Pod service account missing S3 permissions — IAM policy denied all object storage calls.",
        "filename": "30-cloud-iam-denied.log",
        "expected_incident": "CLOUD_IAM_DENIED",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "CLOUD",
    },
    {
        "id": "object-storage-access-failure",
        "title": "Object Storage Access Failure",
        "description": "Application cannot read bootstrap config from S3 — bucket ACL denial.",
        "filename": "31-object-storage-access-failure.log",
        "expected_incident": "OBJECT_STORAGE_ACCESS_FAILURE",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "CLOUD",
    },
    {
        "id": "cloud-rate-limit",
        "title": "Cloud API Rate Limit Exceeded",
        "description": "Inference API returns 429 — request throttling trips circuit breaker.",
        "filename": "32-cloud-rate-limit.log",
        "expected_incident": "CLOUD_RATE_LIMIT",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "CLOUD",
    },
    {
        "id": "capacity-exceeded",
        "title": "Infrastructure Capacity Exceeded",
        "description": "Cloud AZ has no m5.2xlarge capacity — autoscaler cannot provision new nodes.",
        "filename": "33-capacity-exceeded.log",
        "expected_incident": "CAPACITY_EXCEEDED",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "CLOUD",
    },
    # ── Networking / TLS ─────────────────────────────────────────────────────
    {
        "id": "ssl-tls-cert-expired",
        "title": "SSL/TLS Certificate Expired",
        "description": "Let's Encrypt certificate expired 15 days ago — cert-manager renewal failed.",
        "filename": "34-ssl-tls-cert-expired.log",
        "expected_incident": "SSL_TLS_CERTIFICATE_EXPIRED",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "SECURITY",
    },
    {
        "id": "tls-handshake-failure",
        "title": "TLS Handshake Failure",
        "description": "gRPC client cannot verify server certificate — custom CA not in trust store.",
        "filename": "35-tls-handshake-failure.log",
        "expected_incident": "TLS_HANDSHAKE_FAILURE",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "NETWORKING",
    },
    {
        "id": "network-timeout",
        "title": "Network / Connection Timeout",
        "description": "Outbound calls to external API time out repeatedly — circuit breaker opens.",
        "filename": "36-network-timeout.log",
        "expected_incident": "NETWORK_TIMEOUT",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "NETWORKING",
    },
    {
        "id": "http-gateway-error",
        "title": "HTTP 5xx Gateway Error",
        "description": "Ingress returns 502/503 — no healthy upstream pods available to serve traffic.",
        "filename": "37-http-gateway-error.log",
        "expected_incident": "HTTP_GATEWAY_ERROR",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "NETWORKING",
    },
    {
        "id": "service-circuit-breaker",
        "title": "Service Circuit Breaker Open",
        "description": "Downstream failure rate exceeds threshold — circuit breaker trips and blocks calls.",
        "filename": "38-service-circuit-breaker.log",
        "expected_incident": "SERVICE_CIRCUIT_BREAKER_OPEN",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "NETWORKING",
    },
    {
        "id": "load-balancer-unhealthy",
        "title": "Load Balancer Health Check Failure",
        "description": "All ALB target group instances fail health checks — no healthy backends.",
        "filename": "39-load-balancer-unhealthy.log",
        "expected_incident": "LOAD_BALANCER_UNHEALTHY",
        "severity": "ERROR",
        "expected_status": "CONFIDENT",
        "category": "NETWORKING",
    },
    # ── Multi-hop Cascade Scenarios ──────────────────────────────────────────
    {
        "id": "multi-disk-db-cascade",
        "title": "Cascade: Disk Full → DB Failure → CrashLoop",
        "description": "Database volume fills up causing connection failures which trigger a crash loop. (3-hop chain)",
        "filename": "40-multi-disk-db-cascade.log",
        "expected_incident": "DISK_FULL",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "STORAGE",
    },
    {
        "id": "multi-db-deadlock-cascade",
        "title": "Cascade: Slow Query → Deadlock → DB Failure → CrashLoop",
        "description": "Unindexed queries cause lock contention → deadlock → connection exhaustion → crash loop. (4-hop chain)",
        "filename": "41-multi-db-deadlock-cascade.log",
        "expected_incident": "DB_SLOW_QUERY",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "DATABASE",
    },
    {
        "id": "multi-redis-cascade",
        "title": "Cascade: Redis Replication Broken → Timeout → CrashLoop",
        "description": "Broken Redis replica sync causes connection timeouts which prevent service startup. (3-hop chain)",
        "filename": "42-multi-redis-cascade.log",
        "expected_incident": "REDIS_REPLICATION_BROKEN",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "CACHE",
    },
    {
        "id": "multi-tls-cascade",
        "title": "Cascade: Cert Expired → TLS Failure → Auth Denied",
        "description": "Expired TLS certificate prevents secure channel establishment, blocking authentication. (3-hop chain)",
        "filename": "43-multi-tls-cascade.log",
        "expected_incident": "SSL_TLS_CERTIFICATE_EXPIRED",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "SECURITY",
    },
    {
        "id": "multi-cloud-iam-cascade",
        "title": "Cascade: IAM Denied → Storage Fail → Startup Fail → CrashLoop",
        "description": "Missing IAM permissions block bootstrap config read → app cannot start → crash loop. (4-hop chain)",
        "filename": "44-multi-cloud-iam-cascade.log",
        "expected_incident": "CLOUD_IAM_DENIED",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "CLOUD",
    },
    {
        "id": "multi-config-cascade",
        "title": "Cascade: Config Validation → Missing Config → Startup Fail → CrashLoop",
        "description": "Invalid config schema exposes missing required keys → app bootstrap fails → crash loop. (4-hop chain)",
        "filename": "45-multi-config-cascade.log",
        "expected_incident": "CONFIGURATION_VALIDATION_FAILURE",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "CONFIGURATION",
    },
    {
        "id": "multi-network-gateway-cascade",
        "title": "Cascade: Network Timeout → Circuit Breaker → Gateway Error",
        "description": "Persistent timeouts trip circuit breaker → 502/503 gateway errors propagate to clients. (3-hop chain)",
        "filename": "46-multi-network-gateway-cascade.log",
        "expected_incident": "NETWORK_TIMEOUT",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "NETWORKING",
    },
    {
        "id": "multi-dns-tls-cascade",
        "title": "Cascade: DNS Failure → TLS Mismatch → Auth Failure",
        "description": "CoreDNS outage causes hostname resolution failure → TLS cert CN mismatch → auth rejected. (3-hop chain)",
        "filename": "47-multi-dns-tls-cascade.log",
        "expected_incident": "DNS_FAILURE",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "NETWORKING",
    },
    {
        "id": "multi-kafka-cascade",
        "title": "Cascade: Queue Full → Broker Down → Consumer Lag",
        "description": "Topic storage overflow crashes broker → consumer group cannot process any messages. (3-hop chain)",
        "filename": "48-multi-kafka-cascade.log",
        "expected_incident": "QUEUE_FULL",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "MESSAGING",
    },
    {
        "id": "multi-node-evict-cascade",
        "title": "Cascade: Node NotReady → Pod Evicted → CrashLoop",
        "description": "Node failure triggers mass pod eviction → evicted pods enter crash loop on reschedule. (3-hop chain)",
        "filename": "49-multi-node-evict-cascade.log",
        "expected_incident": "NODE_NOT_READY",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "KUBERNETES",
    },
    {
        "id": "multi-quota-cascade",
        "title": "Cascade: Quota Exceeded → Pod Evicted → CrashLoop",
        "description": "Namespace quota enforcement evicts lower-priority pods which restart in a crash loop. (3-hop chain)",
        "filename": "50-multi-quota-cascade.log",
        "expected_incident": "RESOURCE_QUOTA_EXCEEDED",
        "severity": "CRITICAL",
        "expected_status": "CONFIDENT",
        "category": "KUBERNETES",
    },
]


@router.get("")
async def list_scenarios():
    """Return all sample scenarios for the Demo Center."""
    return SCENARIOS


@router.get("/{filename}/content")
async def get_sample_log(filename: str):
    """Return the raw content of a sample log file."""
    # Security: only allow known filenames
    known = {s["filename"] for s in SCENARIOS}
    if filename not in known:
        raise HTTPException(status_code=404, detail=f"Sample '{filename}' not found")

    log_path = SAMPLE_LOGS_DIR / filename
    if not log_path.exists():
        raise HTTPException(
            status_code=404, detail=f"Sample log file '{filename}' not found on disk"
        )

    return {"filename": filename, "content": log_path.read_text()}
